name: Action di Boiocchi
on:
  push:
jobs:
  ciao:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Ciao sono una stringa"
        - run: echo "Ciao sono un'altra stringa"
        - run: python --version
        - run: pip -V
        - run: ls -la
        - run: pwd
        - run: env
        - uses: actions/checkout@v4
          with:
            sparse-Checkout: |
                boiocchi
        - run: ls -la
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12.7'
        - run: python --version