name: Action di Boiocchi
on:
  push:
jobs:
  ciao:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Ciao sono una stringa"
        - run: echo "Ciao sono un'altra stringa"
        - run: ifconfig
        - run: pwd
        - run: ls -la
        - run: env
        